# Generated by Medikit 0.4a5 on 2017-10-29.
# All changes will be overriden.

PACKAGE ?= mused
PYTHON ?= $(shell which python)
PYTHON_BASENAME ?= $(shell basename $(PYTHON))
PYTHON_DIRNAME ?= $(shell dirname $(PYTHON))
PYTHON_REQUIREMENTS_FILE ?= requirements.txt
PYTHON_REQUIREMENTS_DEV_FILE ?= requirements-dev.txt
QUICK ?= 
PIP ?= $(PYTHON_DIRNAME)/pip
PIP_INSTALL_OPTIONS ?= 
DJANGO ?= $(PYTHON) manage.py
YAPF ?= $(PYTHON) -m yapf
YAPF_OPTIONS ?= -rip
VERSION ?= $(shell git describe 2>/dev/null || echo dev)
YARN ?= $(shell which yarn)
NODE ?= $(shell which node)

.PHONY: clean format install install-dev runserver update update-requirements

# Installs the local project dependencies.
install:
	if [ -z "$(QUICK)" ]; then \
	    $(PIP) install -U pip wheel $(PIP_INSTALL_OPTIONS) -r $(PYTHON_REQUIREMENTS_FILE) ; \
	    $(YARN) install --production ; \
	    $(YARN) --version ; \
	fi

# Installs the local project dependencies, including development-only libraries.
install-dev:
	if [ -z "$(QUICK)" ]; then \
	    $(PIP) install -U pip wheel $(PIP_INSTALL_OPTIONS) -r $(PYTHON_REQUIREMENTS_DEV_FILE) ; \
	    $(YARN) install ; \
	fi

# Cleans up the local mess.
clean:
	rm -rf build dist *.egg-info

# Update project artifacts using medikit, after installing it eventually.
update:
	python -c 'import medikit; print(medikit.__version__)' || pip install medikit;
	$(PYTHON) -m medikit update

# Remove requirements files and update project artifacts using medikit, after installing it eventually.
update-requirements:
	rm -rf requirements*.txt
	$(MAKE) update

runserver: install-dev
	$(DJANGO) runserver

format: install-dev
	$(YAPF) $(YAPF_OPTIONS) .
	$(YAPF) $(YAPF_OPTIONS) Projectfile
