# Generated by Django 2.0a1 on 2017-10-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mused', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicgroup',
            name='genres',
            field=models.ManyToManyField(to='mused.MusicGenre'),
        ),
    ]
